### ISSUE TITLE
Add session and oxen wallet

### ISSUE THREAD

**Issue by cryptoxico** [majestrate/debian-lokinet#1]
have a live image with all oxen tools can be interesting for presenting oxen tools easily to someone

**Comment by majestrate** [comment]
fixed in https://github.com/majestrate/debian-lokinet/commit/4d8d07a3cf2ecfe34d9112d86751e0ef9ee40857

will rebuild the iso once a bug with the electron wallet is fixed, currently it cannot install the deb for it on debian stable.

**Comment by majestrate** [comment]
wallet will come later, for now i added session package.

**Comment by majestrate** [comment]
added in https://github.com/majestrate/debian-lokinet/commit/98bac4ec6fc8512989e03bed3f7a7dd48f3c038c
